language: java
jdk:
  - oraclejdk8
  

cache:
    directories:
        - target\angular\node_modules

# safelist
branches:
  only:
  - master

    
deploy:
  provider: heroku
  app: pdb-gateway
  api_key:
    secure: 91c57ec6-4a3a-446a-8224-524d1afc81d7 
  