logging:
  file: app.log
  path: /
  level:
    root: DEBUG

management:
    security:
        enabled : false


zuul:
    ignoredServices: '*'
    routes:
        auth-service-redirect:
            path: /api/auth/**
            sensitiveHeaders:
            url: https://grim-coffin-41549.herokuapp.com/auth/
        auth-service:
            path: /api/**
            sensitiveHeaders:
            url: https://grim-coffin-41549.herokuapp.com/auth/
    addHostHeader: true

ribbon:
  eureka:
    enabled: false