logging:
  level:
    org.apache.tomcat.util.net.NioEndpoint: INFO
    root: DEBUG

management:
    security:
        enabled : false


zuul:
    ignoredServices: '*'
    routes:
        auth-service-redirect:
            path: /login
            sensitiveHeaders:
            url: http://localhost:8888/login
        auth-service:
            path: /api/**
            sensitiveHeaders:
            url: http://localhost:8888/
        drive:
            path: /api-drive/**
            sensitiveHeaders:
            url: http://localhost:9999/client
    
ribbon:
  eureka:
    enabled: false
  restclient:
    enabled: true